# Generated by Django 2.2.3 on 2019-07-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spending',
            options={'ordering': ('-datetime',)},
        ),
        migrations.AlterField(
            model_name='label',
            name='synonym_of',
            field=models.ManyToManyField(blank=True, related_name='_label_synonym_of_+', to='spendings.Label'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='labels',
            field=models.ManyToManyField(blank=True, to='spendings.Label'),
        ),
    ]
